apiVersion: v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
    
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: successtech/k8-network:1
          